import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MyProfilePic from "./components/MyProfilePic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "🏴‍☠️♠️𝕵𝖆𝖆𝖙♠️🏴‍☠️    ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
        <Navbar/>
        {/* <MyProfilePic /> */}
        <main className="px-4 md:px-6 mx-auto">
          {children}
        </main>
        </body>
    </html>
  );
}
